language: node_js
node_js:
  - 12
  - 14
services:
  - redis-server
script:
  - echo 'Starting'
  - npm install
  - echo 'Testing'
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: project-devops20
  on:
    repo: Gabattal/Devops
