version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
  web:
    links:
      - redis
    depends_on:
      - redis
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis
    expose:
      - 3000